// Code generated by "nestcsv"; DO NOT EDIT.

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;

namespace Nestcsv.Example
{

[Serializable]
public partial class ComplexData : TableDataBase
{
    [JsonProperty("Tags")]
    public List<string> Tags;
    [JsonProperty("SKU")]
    public List<SKUData> SKU;
}

public partial class ComplexDB : TableBase
{
    public List<ComplexData> Rows { get; private set; } = new List<ComplexData>();

    public override string TableName => "complex";

    public override object GetRows() => Rows;

    public override void Load(string jsonString)
    {
        Rows = JsonConvert.DeserializeObject<List<ComplexData>>(jsonString)
            ?? new List<ComplexData>();
    }

    private static ComplexDB s_instance;

    public static ComplexDB inst()
    {
        if (s_instance == null)
        {
            s_instance = new ComplexDB();
            var textAsset = Resources.Load<TextAsset>("MetaData/complex");
            if (textAsset != null)
            {
                s_instance.Load(textAsset.text);
            }
            else
            {
                Debug.LogError("[ComplexDB] complex.json not found in Resources/MetaData/");
            }
        }
        return s_instance;
    }
}
}