// Code generated by "nestcsv"; DO NOT EDIT.

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;

namespace Nestcsv.Example
{

[Serializable]
public partial class SKUData : TableDataBase
{
    [JsonProperty("Type")]
    public string Type;
    [JsonProperty("ID")]
    public string ID;
}
}