// Code generated by "nestcsv"; DO NOT EDIT.

using System;
using System.IO;
using UnityEngine;

namespace Nestcsv.Example
{
public abstract class TableBase
{
    public static Func<string, string> TableProvider;

    public abstract string TableName { get; }

    public abstract object GetRows();

    public abstract bool Load(string jsonString);

    public virtual bool LoadFromFile(string basePath)
    {
        var filePath = Path.Combine(basePath, TableName + ".json");
        if (!File.Exists(filePath))
        {
            return false;
        }
        return Load(File.ReadAllText(filePath));
    }

    public virtual bool LoadFromResources(string resourceFolder)
    {
        var resourcePath = string.IsNullOrEmpty(resourceFolder) ? TableName : resourceFolder + "/" + TableName;
        var textAsset = Resources.Load<TextAsset>(resourcePath);
        if (textAsset == null)
        {
            Debug.LogError("[" + GetType().Name + "] " + TableName + ".json not found in Resources/" + resourcePath);
            return false;
        }
        return Load(textAsset.text);
    }
}
}
