// Code generated by "nestcsv"; DO NOT EDIT.

using System.Collections.Generic;

namespace Nestcsv.Example
{
public partial class TableHolder
{
    public ComplexDB Complex { get; } = new ComplexDB();
    public TypesDB Types { get; } = new TypesDB();

    public IReadOnlyList<TableBase> GetTables()
    {
        return new TableBase[]
        {
            Complex,
            Types,
        };
    }

    public TableBase GetTable(string tableName)
    {
        switch (tableName)
        {
            case "complex": return Complex;
            case "types": return Types;
            default: return null;
        }
    }

    public T Get<T>() where T : TableBase
    {
        if (typeof(T) == typeof(ComplexDB)) return (T)(object)Complex;
        if (typeof(T) == typeof(TypesDB)) return (T)(object)Types;
        return null;
    }

    public void LoadFromFile(string basePath)
    {
        foreach (var table in GetTables())
        {
            table.LoadFromFile(basePath);
        }
        Instance = this;
    }

    public static TableHolder LoadFrom(string basePath)
    {
        var holder = new TableHolder();
        holder.LoadFromFile(basePath);
        return holder;
    }

    public void LoadFromResources(string resourceFolder = "MetaData")
    {
        foreach (var table in GetTables())
        {
            table.LoadFromResources(resourceFolder);
        }
        Instance = this;
    }

    public static TableHolder LoadFromResourcesFolder(string resourceFolder = "MetaData")
    {
        var holder = new TableHolder();
        holder.LoadFromResources(resourceFolder);
        return holder;
    }

    public static TableHolder Instance { get; private set; }
}
}
