// Code generated by "nestcsv"; DO NOT EDIT.

using System.Collections.Generic;
using System.Text;

namespace Nestcsv.Example
{
public partial class TableHolder
{
    public ComplexDB Complex { get; } = new ComplexDB();
    public TypesDB Types { get; } = new TypesDB();

    public IReadOnlyList<TableBase> GetTables()
    {
        return new TableBase[]
        {
            Complex,
            Types,
        };
    }

    public TableBase GetTable(string tableName)
    {
        switch (tableName)
        {
            case "complex": return Complex;
            case "types": return Types;
            default: return null;
        }
    }

    public T Get<T>() where T : TableBase
    {
        if (typeof(T) == typeof(ComplexDB)) return (T)(object)Complex;
        if (typeof(T) == typeof(TypesDB)) return (T)(object)Types;
        return null;
    }

    public void LoadFromFile(string basePath)
    {
        foreach (var table in GetTables())
        {
            table.LoadFromFile(basePath);
        }
        Instance = this;
    }

    public static TableHolder LoadFrom(string basePath)
    {
        var holder = new TableHolder();
        holder.LoadFromFile(basePath);
        return holder;
    }

    public bool LoadFromJsonMap(IReadOnlyDictionary<string, string> jsonBySheet)
    {
        var success = true;
        foreach (var kv in jsonBySheet)
        {
            var table = GetTable(kv.Key);
            if (table == null || !table.Load(kv.Value))
            {
                success = false;
            }
        }
        return success;
    }

    public bool LoadFromBytesMap(IReadOnlyDictionary<string, byte[]> bytesBySheet)
    {
        var success = true;
        foreach (var kv in bytesBySheet)
        {
            var table = GetTable(kv.Key);
            if (table == null || !table.Load(Encoding.UTF8.GetString(kv.Value)))
            {
                success = false;
            }
        }
        return success;
    }

    public void LoadFromResources(string resourceFolder = "MetaData")
    {
        foreach (var table in GetTables())
        {
            table.LoadFromResources(resourceFolder);
        }
        Instance = this;
    }

    public static TableHolder LoadFromResourcesFolder(string resourceFolder = "MetaData")
    {
        var holder = new TableHolder();
        holder.LoadFromResources(resourceFolder);
        return holder;
    }

    public static TableHolder Instance { get; private set; }

    public static void Register(TableHolder holder)
    {
        Instance = holder;
    }
}
}
