// Code generated by "nestcsv"; DO NOT EDIT.

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEngine;

namespace Nestcsv.Example
{

[Serializable]
public partial class TypesData : TableDataBase
{
    [JsonProperty("Int")]
    public int Int;
    [JsonProperty("Long")]
    public long Long;
    [JsonProperty("Float")]
    public double Float;
    [JsonProperty("String")]
    public string String;
    [JsonProperty("Time")]
    public DateTime Time;
    [JsonProperty("Json")]
    public JToken Json;
    [JsonProperty("IntArray")]
    public List<int> IntArray;
    [JsonProperty("LongArray")]
    public List<long> LongArray;
    [JsonProperty("FloatArray")]
    public List<double> FloatArray;
    [JsonProperty("StringArray")]
    public List<string> StringArray;
    [JsonProperty("TimeArray")]
    public List<DateTime> TimeArray;
}

public partial class TypesDB : TableBase
{
    public Dictionary<int, TypesData> Rows { get; private set; } = new Dictionary<int, TypesData>();

    public override string TableName => "types";

    public override object GetRows() => Rows;

    public override bool Load(string jsonString)
    {
        var result = JsonConvert.DeserializeObject<Dictionary<int, TypesData>>(jsonString);
        if (result == null) return false;
        Rows = result;
        return true;
    }

    public TypesData Find(int id)
    {
        return Rows.TryGetValue(id, out var row) ? row : null;
    }

    public bool TryFind(int id, out TypesData row)
    {
        row = Find(id);
        return row != null;
    }

    public TypesData FindOrThrow(int id)
    {
        var row = Find(id);
        if (row == null)
        {
            throw new KeyNotFoundException("[" + GetType().Name + "] row with id '" + id + "' not found in " + TableName);
        }
        return row;
    }

    private static TypesDB s_instance;

    public static TypesDB inst()
    {
        if (s_instance == null)
        {
            s_instance = new TypesDB();
            var providerJson = TableBase.TableProvider?.Invoke("types");
            if (providerJson != null)
            {
                s_instance.Load(providerJson);
            }
            else
            {
                var textAsset = Resources.Load<TextAsset>("MetaData/types");
                if (textAsset != null)
                {
                    s_instance.Load(textAsset.text);
                }
                else
                {
                    Debug.LogError("[TypesDB] types.json not found in Resources/MetaData/");
                }
            }
        }
        return s_instance;
    }
}
}