// Code generated by "nestcsv"; DO NOT EDIT.

#pragma once

#include "Json.h"
#include "NestTableBase.generated.h"

USTRUCT(BlueprintType)
struct FNestTableBase
{
    GENERATED_BODY()

    FNestTableBase() {}
    virtual ~FNestTableBase() {}

    virtual FString GetSheetName() const { return TEXT(""); }
    virtual void Load(const TSharedPtr<FJsonValue>& JsonValue) {}
};
