// Code generated by "nestcsv"; DO NOT EDIT.

package clienttable

type Tables struct {
	SampleData SampleDataTable
}

func LoadTablesFromFile(basePath string) (*Tables, error) {
	var t Tables
	if err := t.SampleData.LoadFromFile(basePath); err != nil {
		return nil, err
	}
	return &t, nil
}

func (t *Tables) GetTables() []TableBase {
	return []TableBase{
		&t.SampleData,
	}
}

func (t *Tables) GetBySheetName(sheetName string) TableBase {
	switch sheetName {
	case "sample-data":
		return &t.SampleData
	default:
		return nil
	}
}
