// Code generated by "nestcsv"; DO NOT EDIT.

package table

import (
	"encoding/json"
	"os"
	"path/filepath"
)

type ComplexSKU struct {
	Type string `json:"Type"`
	ID   string `json:"ID"`
}

type Complex struct {
	ID      int          `json:"ID"`
	SKU     []ComplexSKU `json:"SKU"`
	Rewards []Reward     `json:"Rewards"`
}

type ComplexTable struct {
	Rows []Complex
}

func (t *ComplexTable) SheetName() string {
	return "complex"
}

func (t *ComplexTable) GetRows() interface{} {
	return t.Rows
}

func (t *ComplexTable) Load(data []byte) error {
	return json.Unmarshal(data, &t.Rows)
}

func (t *ComplexTable) LoadFromString(jsonString string) error {
	return t.Load([]byte(jsonString))
}

func (t *ComplexTable) LoadFromFile(basePath string) error {
	file, err := os.Open(filepath.Join(basePath, "complex.json"))
	if err != nil {
		return err
	}
	defer file.Close()

	return json.NewDecoder(file).Decode(&t.Rows)
}
