// Code generated by "nestcsv"; DO NOT EDIT.

package table

type Tables struct {
	Complex ComplexTable
	Types   TypesTable
}

func LoadTablesFromFile(basePath string) (*Tables, error) {
	var t Tables
	if err := t.Complex.LoadFromFile(basePath); err != nil {
		return nil, err
	}
	if err := t.Types.LoadFromFile(basePath); err != nil {
		return nil, err
	}
	return &t, nil
}

func (t *Tables) GetTables() []TableBase {
	return []TableBase{
		&t.Complex,
		&t.Types,
	}
}

func (t *Tables) GetBySheetName(sheetName string) TableBase {
	switch sheetName {
	case "complex":
		return &t.Complex
	case "types":
		return &t.Types
	default:
		return nil
	}
}
