// Code generated by "nestcsv"; DO NOT EDIT.

package table

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"time"
)

type Types struct {
	Int         int         `json:"Int"`
	Long        int64       `json:"Long"`
	Float       float64     `json:"Float"`
	String      string      `json:"String"`
	Time        time.Time   `json:"Time"`
	Json        interface{} `json:"Json"`
	IntArray    []int       `json:"IntArray"`
	LongArray   []int64     `json:"LongArray"`
	FloatArray  []float64   `json:"FloatArray"`
	StringArray []string    `json:"StringArray"`
	TimeArray   []time.Time `json:"TimeArray"`
}

type TypesTable struct {
	Rows map[string]Types
}

func (t *TypesTable) SheetName() string {
	return "types"
}

func (t *TypesTable) GetRows() interface{} {
	return t.Rows
}

func (t *TypesTable) Find(id int) (*Types, bool) {
	if row, ok := t.Rows[strconv.Itoa(id)]; ok {
		return &row, true
	}
	return nil, false
}

func (t *TypesTable) Load(data []byte) error {
	return json.Unmarshal(data, &t.Rows)
}

func (t *TypesTable) LoadFromString(jsonString string) error {
	return t.Load([]byte(jsonString))
}

func (t *TypesTable) LoadFromFile(basePath string) error {
	file, err := os.Open(filepath.Join(basePath, "types.json"))
	if err != nil {
		return err
	}
	defer file.Close()

	return json.NewDecoder(file).Decode(&t.Rows)
}
