{{- with .File -}}
// Code generated by "nestcsv"; YOU CAN ONLY EDIT WITHIN THE TAGGED REGIONS!

#pragma once

#include "{{ $.Prefix }}TableDataBase.h"
{{- range .FileRefs }}
#include "{{ $.Prefix }}{{ pascal .Name }}.h"
{{- end }}

{{ $extraInclude := list $.Prefix .Name "_EXTRA_INCLUDE" | join "" | upper -}}
//NESTCSV:{{ $extraInclude }}_START
{{ index $.ExistingContent $extraInclude | default "" }}
//NESTCSV:{{ $extraInclude }}_END

#include "{{ $.Prefix }}{{ pascal .Name }}.generated.h"
{{ range append .AnonymousStructs .Struct }}
USTRUCT(BlueprintType)
struct F{{ $.Prefix }}{{ pascal .Name }} : public F{{ $.Prefix }}TableDataBase
{
    GENERATED_BODY()

    {{- range .Fields }}
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    {{ fieldType . }} {{ .Name }};
    {{- end }}

    virtual bool Load(const TSharedPtr<FJsonObject>& JsonObject) override
    {
        if (!JsonObject.IsValid()) return false;
        F{{ $.Prefix }}{{ pascal .Name }} _Result;
{{/**/}}
        {{- range .Fields }}
        {{- if .IsArray }}
        {
            const TArray<TSharedPtr<FJsonValue>>* {{ .Name }}Array = nullptr;
            if (!JsonObject.ToSharedRef()->TryGetArrayField(TEXT("{{ .Name }}"), {{ .Name }}Array)) return false;
            for (const auto& Item : *{{ .Name }}Array)
            {
                {{- if eq .Type "time" }}
                FString DateTimeStr;
                if (!Item->TryGetString(DateTimeStr)) return false;
                FDateTime DateTime;
                if (!FDateTime::ParseIso8601(DateTimeStr, DateTime)) return false;
                _Result.{{ .Name }}.Add(DateTime);
                {{- else if eq .Type "json" }}
                _Result.{{ .Name }}.Add(Item);
                {{- else if eq .Type "struct" }}
                const TSharedPtr<FJsonObject> *ObjPtr = nullptr;
                if (!Item->TryGetObject(ObjPtr)) return false;
                {{ fieldElemType . }} FieldItem;
                FieldItem.Load(*ObjPtr);
                _Result.{{ .Name }}.Add(FieldItem);
                {{- else }}
                {{ fieldElemType . }} FieldItem;
                {{- if eq .Type "int" }}
                if (!Item->TryGetNumber(FieldItem)) return false;
                {{- else if eq .Type "long" }}
                if (!Item->TryGetNumber(FieldItem)) return false;
                {{- else if eq .Type "float" }}
                if (!Item->TryGetNumber(FieldItem)) return false;
                {{- else if eq .Type "bool" }}
                if (!Item->TryGetBool(FieldItem)) return false;
                {{- else if eq .Type "string" }}
                if (!Item->TryGetString(FieldItem)) return false;
                {{- end }}
                _Result.{{ .Name }}.Add(FieldItem);
                {{- end }}
            }
        }
        {{- else if eq .Type "int" }}
        if (!JsonObject.ToSharedRef()->TryGetNumberField(TEXT("{{ .Name }}"), _Result.{{ .Name }})) return false;
        {{- else if eq .Type "long" }}
        if (!JsonObject.ToSharedRef()->TryGetNumberField(TEXT("{{ .Name }}"), _Result.{{ .Name }})) return false;
        {{- else if eq .Type "float" }}
        if (!JsonObject.ToSharedRef()->TryGetNumberField(TEXT("{{ .Name }}"), _Result.{{ .Name }})) return false;
        {{- else if eq .Type "bool" }}
        if (!JsonObject.ToSharedRef()->TryGetBoolField(TEXT("{{ .Name }}"), _Result.{{ .Name }})) return false;
        {{- else if eq .Type "string" }}
        if (!JsonObject.ToSharedRef()->TryGetStringField(TEXT("{{ .Name }}"), _Result.{{ .Name }})) return false;
        {{- else if eq .Type "time" }}
        {
            FString {{ .Name }}DtStr;
            if (!JsonObject.ToSharedRef()->TryGetStringField(TEXT("{{ .Name }}"), {{ .Name }}DtStr)) return false;
            if (!FDateTime::ParseIso8601(*{{ .Name }}DtStr, _Result.{{ .Name }})) return false;
        }
        {{- else if eq .Type "json" }}
        if (!JsonObject.ToSharedRef()->TryGetField(TEXT("{{ .Name }}"), _Result.{{ .Name }})) return false;
        {{- else if eq .Type "struct" }}
        {
            const TSharedPtr<FJsonObject> *{{ .Name }}ObjPtr = nullptr;
            if (!JsonObject.ToSharedRef()->TryGetObjectField(TEXT("{{ .Name }}"), {{ .Name }}ObjPtr)) return false;
            _Result.{{ .Name }}.Load(*{{ .Name }}ObjPtr);
        }
        {{- end }}
        {{- end }}

        *this = MoveTemp(_Result);
        return true;
    }

    {{ $extraBody := list $.Prefix .Name "_EXTRA_BODY" | join "" | upper -}}
    //NESTCSV:{{ $extraBody }}_START
    {{ index $.ExistingContent $extraBody | default "" }}
    //NESTCSV:{{ $extraBody }}_END
};
{{ end }}
{{- end -}}
