// Code generated by "nestcsv"; DO NOT EDIT.

#pragma once

{{- range .Tables }}
#include "{{ $.Prefix }}{{ pascal .Name }}Table.hpp"
{{- end }}

UCLASS(BlueprintType)
class U{{ .Prefix }}TableHolder : public UObject
{
    GENERATED_BODY()

public:
    U{{ .Prefix }}TableHolder() :
    {{- range .Tables }}
        {{ pascal .Name }}(MakeUnique<F{{ $.Prefix }}{{ pascal .Name }}Table>()){{ if ne . (last $.Tables) }},{{ end }}
    {{- end }}
        {}
    virtual ~U{{ .Prefix }}TableHolder() override {}

    {{ range .Tables }}
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TUniquePtr<F{{ $.Prefix }}{{ pascal .Name }}Table> {{ pascal .Name }};
    {{- end }}

    {{/* FIXME: this method maybe can select return value directly */ -}}
    UFUNCTION(BlueprintCallable)
    F{{ .Prefix }}TableBase* GetBySheetName(FString SheetName) const
    {
        {{- range .Tables }}
        if (SheetName == TEXT("{{ .Name }}"))
        {
            return {{ pascal .Name }}.Get();
        }
        {{- end }}
        return nullptr;
    }
};
