// Code generated by "nestcsv"; DO NOT EDIT.

#pragma once


#include "NestComplexTable.h"
#include "NestTypesTable.h"
#include "NestTableHolder.generated.h"

UCLASS(BlueprintType)
class UNestTableHolder : public UObject
{
    GENERATED_BODY()

public:
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    FNestComplexTable Complex;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    FNestTypesTable Types;

    TArray<FNestTableBase*> GetTables()
    {
        return {
            &Complex,
            &Types,
        };
    }

    FNestTableBase* GetBySheetName(const FString& SheetName)
    {
        if (SheetName == Complex.GetSheetName()) return &Complex;
        if (SheetName == Types.GetSheetName()) return &Types;
        return nullptr;
    }

    template <class T = FNestTableBase>
    T* Get()
    {
        if constexpr (std::is_same_v<T, FNestComplexTable>) return &Complex;
        if constexpr (std::is_same_v<T, FNestTypesTable>) return &Types;
        return nullptr;
    }
};
