// Code generated by "nestcsv"; YOU CAN ONLY EDIT WITHIN THE TAGGED REGIONS!

#pragma once

#include "NestTableDataBase.h"

//nestcsv:additional_include_start

//nestcsv:additional_include_end

#include "NestSKU.generated.h"

USTRUCT(BlueprintType)
struct FNestSKU : public FNestTableDataBase
{
    GENERATED_BODY()
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    FString Type;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    FString ID;

    virtual void Load(const TSharedPtr<FJsonObject>& JsonObject) override
    {
        JsonObject.ToSharedRef()->TryGetStringField(TEXT("Type"), Type);
        JsonObject.ToSharedRef()->TryGetStringField(TEXT("ID"), ID);
    }

    //nestcsv:additional_struct_body_start
    
    //nestcsv:additional_struct_body_end
};
