// Code generated by "nestcsv"; YOU CAN ONLY EDIT WITHIN THE TAGGED REGIONS!

#pragma once

#include "NestTableBase.h"
#include "NestComplex.h"

//nestcsv:additional_include_start
#include "CustomInclude.h"
//nestcsv:additional_include_end

#include "NestComplexTable.generated.h"

USTRUCT(BlueprintType)
struct FNestComplexTable : public FNestTableBase
{
    GENERATED_BODY()

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    TArray<FNestComplex> Rows;
    
    virtual FString GetSheetName() const override
    {
        return TEXT("complex");
    }

    virtual void Load(const TSharedPtr<FJsonValue>& JsonValue) override
    {
        const TArray<TSharedPtr<FJsonValue>>* RowsArray = nullptr;
        if (JsonValue->TryGetArray(RowsArray))
        {
            for (const auto& Row : *RowsArray)
            {
                const TSharedPtr<FJsonObject> *RowValue = nullptr;
                if (Row->TryGetObject(RowValue))
                {
                    FNestComplex RowItem;
                    RowItem.Load(*RowValue);
                    Rows.Add(RowItem);
                }
            }
        }
    }

    //nestcsv:additional_struct_body_start
    void CustomFunction()
    {
        // Custom function body
    }
    //nestcsv:additional_struct_body_end
};