// Code generated by "nestcsv"; YOU CAN ONLY EDIT WITHIN THE TAGGED REGIONS!

#pragma once

#include "NestTableBase.h"
#include "NestComplex.h"

//NESTCSV:NESTCOMPLEX_EXTRA_INCLUDE_START
#include "CustomInclude.h"
//NESTCSV:NESTCOMPLEX_EXTRA_INCLUDE_END

#include "NestComplexTable.generated.h"

USTRUCT(BlueprintType)
struct FNestComplexTable : public FNestTableBase
{
    GENERATED_BODY()

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    TArray<FNestComplex> Rows;
    
    virtual FString GetSheetName() const override
    {
        return TEXT("complex");
    }

    virtual bool Load(const TSharedPtr<FJsonValue>& JsonValue) override
    {
        if (!JsonValue.IsValid()) return false;
        TArray<FNestComplex> _Result;

        const TArray<TSharedPtr<FJsonValue>>* RowsArray = nullptr;
        if (!JsonValue->TryGetArray(RowsArray)) return false;
        for (const auto& Row : *RowsArray)
        {
            const TSharedPtr<FJsonObject> *RowValue = nullptr;
            if (!Row->TryGetObject(RowValue)) return false;
            FNestComplex RowItem;
            if (!RowItem.Load(*RowValue)) return false;
            _Result.Add(RowItem);
        }

        Rows = MoveTemp(_Result);
        return true;
    }

    //NESTCSV:NESTCOMPLEX_EXTRA_BODY_START
    void CustomFunction()
    {
        // Custom function body
    }
    //NESTCSV:NESTCOMPLEX_EXTRA_BODY_END
};