// Code generated by "nestcsv"; YOU CAN ONLY EDIT WITHIN THE TAGGED REGIONS!

#pragma once

#include "NestTableDataBase.h"

//NESTCSV:NESTSKU_EXTRA_INCLUDE_START

//NESTCSV:NESTSKU_EXTRA_INCLUDE_END

#include "NestSKU.generated.h"

USTRUCT(BlueprintType)
struct FNestSKU : public FNestTableDataBase
{
    GENERATED_BODY()
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    FString Type;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    FString ID;

    virtual bool Load(const TSharedPtr<FJsonObject>& JsonObject) override
    {
        if (!JsonObject.IsValid()) return false;
        FNestSKU _Result;

        if (!JsonObject.ToSharedRef()->TryGetStringField(TEXT("Type"), _Result.Type)) return false;
        if (!JsonObject.ToSharedRef()->TryGetStringField(TEXT("ID"), _Result.ID)) return false;

        *this = MoveTemp(_Result);
        return true;
    }

    //NESTCSV:NESTSKU_EXTRA_BODY_START
    
    //NESTCSV:NESTSKU_EXTRA_BODY_END
};
