// Code generated by "nestcsv"; DO NOT EDIT.

#pragma once

#include "Json.h"
#include "NestTableDataBase.generated.h"

USTRUCT(BlueprintType)
struct FNestTableDataBase
{
    GENERATED_BODY()

    FNestTableDataBase() {}
    virtual ~FNestTableDataBase() {}

    virtual bool Load(const TSharedPtr<FJsonObject>& JsonObject) { return false; }
    virtual bool Load(const FString& JsonString)
    {
        TSharedPtr<FJsonObject> JsonObject;
        TSharedRef<TJsonReader<TCHAR>> JsonReader = TJsonReaderFactory<TCHAR>::Create(JsonString);
        if (FJsonSerializer::Deserialize(JsonReader, JsonObject) && JsonObject.IsValid())
        {
            return Load(JsonObject);
        }
        return false;
    }
};
