// Code generated by "nestcsv"; YOU CAN ONLY EDIT WITHIN THE TAGGED REGIONS!

#pragma once

#include "NestTableDataBase.h"

//NESTCSV:NESTTYPES_EXTRA_INCLUDE_START

//NESTCSV:NESTTYPES_EXTRA_INCLUDE_END

#include "NestTypes.generated.h"

USTRUCT(BlueprintType)
struct FNestTypes : public FNestTableDataBase
{
    GENERATED_BODY()
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    int32 Int;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    int64 Long;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    double Float;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    FString String;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    FDateTime Time;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    TSharedPtr<FJsonValue> Json;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    TArray<int32> IntArray;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    TArray<int64> LongArray;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    TArray<double> FloatArray;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    TArray<FString> StringArray;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    TArray<FDateTime> TimeArray;

    virtual void Load(const TSharedPtr<FJsonObject>& JsonObject) override
    {
        JsonObject.ToSharedRef()->TryGetNumberField(TEXT("Int"), Int);
        JsonObject.ToSharedRef()->TryGetNumberField(TEXT("Long"), Long);
        JsonObject.ToSharedRef()->TryGetNumberField(TEXT("Float"), Float);
        JsonObject.ToSharedRef()->TryGetStringField(TEXT("String"), String);
        FString TimeDtStr;
        if (JsonObject.ToSharedRef()->TryGetStringField(TEXT("Time"), TimeDtStr))
        {
            FDateTime::ParseIso8601(*TimeDtStr, Time);
        }
        JsonObject.ToSharedRef()->TryGetField(TEXT("Json"), Json);
        const TArray<TSharedPtr<FJsonValue>>* IntArrayArray = nullptr;
        if (JsonObject.ToSharedRef()->TryGetArrayField(TEXT("IntArray"), IntArrayArray))
        {
            for (const auto& Item : *IntArrayArray)
            {
                int32 FieldItem;
                if (Item->TryGetNumber(FieldItem))
                {
                    IntArray.Add(FieldItem);
                }
            }
        }
        const TArray<TSharedPtr<FJsonValue>>* LongArrayArray = nullptr;
        if (JsonObject.ToSharedRef()->TryGetArrayField(TEXT("LongArray"), LongArrayArray))
        {
            for (const auto& Item : *LongArrayArray)
            {
                int64 FieldItem;
                if (Item->TryGetNumber(FieldItem))
                {
                    LongArray.Add(FieldItem);
                }
            }
        }
        const TArray<TSharedPtr<FJsonValue>>* FloatArrayArray = nullptr;
        if (JsonObject.ToSharedRef()->TryGetArrayField(TEXT("FloatArray"), FloatArrayArray))
        {
            for (const auto& Item : *FloatArrayArray)
            {
                double FieldItem;
                if (Item->TryGetNumber(FieldItem))
                {
                    FloatArray.Add(FieldItem);
                }
            }
        }
        const TArray<TSharedPtr<FJsonValue>>* StringArrayArray = nullptr;
        if (JsonObject.ToSharedRef()->TryGetArrayField(TEXT("StringArray"), StringArrayArray))
        {
            for (const auto& Item : *StringArrayArray)
            {
                FString FieldItem;
                if (Item->TryGetString(FieldItem))
                {
                    StringArray.Add(FieldItem);
                }
            }
        }
        const TArray<TSharedPtr<FJsonValue>>* TimeArrayArray = nullptr;
        if (JsonObject.ToSharedRef()->TryGetArrayField(TEXT("TimeArray"), TimeArrayArray))
        {
            for (const auto& Item : *TimeArrayArray)
            {
                FString DateTimeStr;
                if (Item->TryGetString(DateTimeStr))
                {
                    FDateTime DateTime;
                    if (FDateTime::ParseIso8601(DateTimeStr, DateTime))
                    {
                        TimeArray.Add(DateTime);
                    }
                }
            }
        }
    }

    //NESTCSV:NESTTYPES_EXTRA_BODY_START
    
    //NESTCSV:NESTTYPES_EXTRA_BODY_END
};
