// Code generated by "nestcsv"; YOU CAN ONLY EDIT WITHIN THE TAGGED REGIONS!

#pragma once

#include "NestTableBase.h"
#include "NestTypes.h"

//nestcsv:additional_include_start

//nestcsv:additional_include_end

#include "NestTypesTable.generated.h"

USTRUCT(BlueprintType)
struct FNestTypesTable : public FNestTableBase
{
    GENERATED_BODY()

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    TMap<FString, FNestTypes> Rows;
    
    virtual FString GetSheetName() const override
    {
        return TEXT("types");
    }

    virtual void Load(const TSharedPtr<FJsonValue>& JsonValue) override
    {
        const TSharedPtr<FJsonObject>* RowsMap = nullptr;
        if (JsonValue->TryGetObject(RowsMap))
        {
            for (const auto& Row : (*RowsMap)->Values)
            {
                const TSharedPtr<FJsonObject> *RowValue = nullptr;
                if (Row.Value->TryGetObject(RowValue))
                {
                    FNestTypes RowItem;
                    RowItem.Load(*RowValue);
                    Rows.Add(Row.Key, RowItem);
                }
            }
        }
    }

    //nestcsv:additional_struct_body_start
    
    //nestcsv:additional_struct_body_end
};