// Code generated by "nestcsv"; DO NOT EDIT.

package table

import (
	"encoding/json"
	"os"
)

type Complex struct {
	ID   int      `json:"ID"`
	Tags []string `json:"Tags"`
	SKU  []struct {
		Type string `json:"Type"`
		ID   string `json:"ID"`
	} `json:"SKU"`
	Rewards []Reward `json:"Rewards"`
}

type ComplexTable struct {
	Rows []Complex
}

func (t *ComplexTable) SheetName() string {
	return "complex"
}

func (t *ComplexTable) Load() error {
	file, err := os.Open("../json/complex.json")
	if err != nil {
		return err
	}
	defer file.Close()

	return json.NewDecoder(file).Decode(&t.Rows)
}
