// Code generated by "nestcsv"; DO NOT EDIT.

package table

import (
	"crypto/md5"
	"encoding/hex"
	"encoding/json"
	"os"
)

type ComplexSKU struct {
	Type string `json:"Type"`
	ID   string `json:"ID"`
}

type Complex struct {
	ID      int          `json:"ID"`
	SKU     []ComplexSKU `json:"SKU"`
	Rewards []Reward     `json:"Rewards"`
}

type ComplexTable struct {
	Rows     []Complex
	rawData  []byte
	checksum string
}

func (t *ComplexTable) SheetName() string {
	return "complex"
}

func (t *ComplexTable) Load() error {
	file, err := os.Open("../json/server/complex.json")
	if err != nil {
		return err
	}
	defer file.Close()

	if err := json.NewDecoder(file).Decode(&t.Rows); err != nil {
		return err
	}
	t.rawData, err = json.Marshal(t.Rows)
	if err != nil {
		return err
	}
	checksum := md5.Sum(t.Data)
	t.checksum = hex.EncodeToString(checksum[:])
	return nil
}
func (t *ComplexTable) RawData() ([]byte, string) {
	return t.rawData, t.checksum
}
