// Code generated by "nestcsv"; DO NOT EDIT.

package table

type Tables struct {
	Complex ComplexTable
	Types   TypesTable
}

func LoadTables() (*Tables, error) {
	var t Tables
	if err := t.Complex.Load(); err != nil {
		return nil, err
	}
	if err := t.Types.Load(); err != nil {
		return nil, err
	}
	return &t, nil
}

func (t *Tables) GetBySheetName(sheetName string) TableBase {
	switch sheetName {
	case "complex":
		return &t.Complex
	case "types":
		return &t.Types
	default:
		return nil
	}
}
