// Code generated by "nestcsv"; DO NOT EDIT.

package table

type Reward struct {
	Type       string `json:"Type"`
	ParamType  string `json:"ParamType"`
	ParamValue struct {
		Int   int     `json:"Int"`
		Float float64 `json:"Float"`
		Str   string  `json:"Str"`
	} `json:"ParamValue"`
}
