// Code generated by "nestcsv"; DO NOT EDIT.

package table

import (
	"crypto/md5"
	"encoding/hex"
	"encoding/json"
	"os"
	"time"
)

type Types struct {
	Int         int         `json:"Int"`
	Long        int64       `json:"Long"`
	Float       float64     `json:"Float"`
	String      string      `json:"String"`
	Time        time.Time   `json:"Time"`
	Json        interface{} `json:"Json"`
	IntArray    []int       `json:"IntArray"`
	LongArray   []int64     `json:"LongArray"`
	FloatArray  []float64   `json:"FloatArray"`
	StringArray []string    `json:"StringArray"`
	TimeArray   []time.Time `json:"TimeArray"`
}

type TypesTable struct {
	Rows     map[string]Types
	rawData  []byte
	checksum string
}

func (t *TypesTable) SheetName() string {
	return "types"
}

func (t *TypesTable) Load() error {
	file, err := os.Open("../json/server/types.json")
	if err != nil {
		return err
	}
	defer file.Close()

	if err := json.NewDecoder(file).Decode(&t.Rows); err != nil {
		return err
	}
	t.rawData, err = json.Marshal(t.Rows)
	if err != nil {
		return err
	}
	checksum := md5.Sum(t.Data)
	t.checksum = hex.EncodeToString(checksum[:])
	return nil
}
func (t *TypesTable) RawData() ([]byte, string) {
	return t.rawData, t.checksum
}
