// Code generated by "nestcsv"; DO NOT EDIT.

package table

const (
	SampleDataName = "sample-data"
)

type TableHolder struct {
	SampleData SampleDataTable
}

func LoadTablesFromFile(basePath string) (*TableHolder, error) {
	var t TableHolder
	if err := t.SampleData.LoadFromFile(basePath); err != nil {
		return nil, err
	}
	return &t, nil
}

type TableBase interface {
	TableName() string
	GetRows() interface{}
	Load(data []byte) error
	LoadFromString(jsonString string) error
	LoadFromFile(basePath string) error
}

func (t *TableHolder) GetTables() []TableBase {
	return []TableBase{
		&t.SampleData,
	}
}

func (t *TableHolder) GetTable(tableName string) TableBase {
	switch tableName {
	case SampleDataName:
		return &t.SampleData
	default:
		return nil
	}
}
