// Code generated by "nestcsv"; DO NOT EDIT.

package table

import (
	"encoding/json"
	"os"
	"path/filepath"
)

type SampleData struct {
	ID         int32  `json:"ID"`
	ClientData string `json:"ClientData"`
	CommonData string `json:"CommonData"`
}

type SampleDataTable struct {
	Rows []SampleData
}

func (t *SampleDataTable) TableName() string {
	return SampleDataName
}

func (t *SampleDataTable) GetRows() interface{} {
	return t.Rows
}

func (t *SampleDataTable) Find(id int32) (*SampleData, bool) {
	for _, row := range t.Rows {
		if row.ID == id {
			return &row, true
		}
	}
	return nil, false
}

func (t *SampleDataTable) Load(data []byte) error {
	return json.Unmarshal(data, &t.Rows)
}

func (t *SampleDataTable) LoadFromString(jsonString string) error {
	return t.Load([]byte(jsonString))
}

func (t *SampleDataTable) LoadFromFile(basePath string) error {
	file, err := os.Open(filepath.Join(basePath, "sample-data.json"))
	if err != nil {
		return err
	}
	defer file.Close()

	return json.NewDecoder(file).Decode(&t.Rows)
}
