{{- with .File -}}
// Code generated by "nestcsv"; DO NOT EDIT.

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
{{- if has .FieldTypes "json" }}
using Newtonsoft.Json.Linq;
{{- end }}
{{- if $.ResourceFolder }}
using UnityEngine;
{{- end }}
{{ if $.Namespace }}
namespace {{ $.Namespace }}
{
{{ end -}}
{{- range $i, $s := append .AnonymousStructs .Struct }}
{{ if $i }}
{{ end -}}
[Serializable]
public partial class {{ $.Prefix }}{{ pascal $s.Name }}{{ $.DataSuffix }} : {{ $.Prefix }}TableDataBase
{
{{- range $s.Fields }}
    [JsonProperty("{{ .Name }}")]
    public {{ fieldType . }} {{ pascal .Name }};
{{- end }}
}
{{- end }}
{{- if .IsTable }}

public partial class {{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.TableSuffix }} : {{ $.Prefix }}TableBase
{
{{- if .IsMap }}
    public Dictionary<{{ fieldPrimitiveType .IDFieldType }}, {{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.DataSuffix }}> Rows { get; private set; } = new Dictionary<{{ fieldPrimitiveType .IDFieldType }}, {{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.DataSuffix }}>();
{{- else }}
    public List<{{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.DataSuffix }}> Rows { get; private set; } = new List<{{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.DataSuffix }}>();
{{- end }}

    public override string TableName => "{{ .Name }}";

    public override object GetRows() => Rows;

    public override bool Load(string jsonString)
    {
{{- if .IsMap }}
        var result = JsonConvert.DeserializeObject<Dictionary<{{ fieldPrimitiveType .IDFieldType }}, {{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.DataSuffix }}>>(jsonString);
        if (result == null) return false;
        Rows = result;
{{- else }}
        var result = JsonConvert.DeserializeObject<List<{{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.DataSuffix }}>>(jsonString);
        if (result == null) return false;
        Rows = result;
{{- end }}
        return true;
    }
{{- if or .IDField .IsMap }}

    public {{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.DataSuffix }} Find({{ fieldPrimitiveType .IDFieldType }} id)
    {
{{- if .IsMap }}
        return Rows.TryGetValue(id, out var row) ? row : null;
{{- else }}
        return Rows.Find(row => row.{{ pascal .IDField.Name }} == id);
{{- end }}
    }

    public bool TryFind({{ fieldPrimitiveType .IDFieldType }} id, out {{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.DataSuffix }} row)
    {
        row = Find(id);
        return row != null;
    }

    public {{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.DataSuffix }} FindOrThrow({{ fieldPrimitiveType .IDFieldType }} id)
    {
        var row = Find(id);
        if (row == null)
        {
            throw new KeyNotFoundException("[" + GetType().Name + "] row with id '" + id + "' not found in " + TableName);
        }
        return row;
    }
{{- end }}
{{- if $.ResourceFolder }}

    private static {{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.TableSuffix }} s_instance;

    public static {{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.TableSuffix }} inst()
    {
        if (s_instance == null)
        {
            s_instance = new {{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.TableSuffix }}();
            var providerJson = {{ $.Prefix }}TableBase.TableProvider?.Invoke("{{ .Name }}");
            if (providerJson != null)
            {
                s_instance.Load(providerJson);
            }
            else
            {
                var textAsset = Resources.Load<TextAsset>("{{ $.ResourceFolder }}/{{ .Name }}");
                if (textAsset != null)
                {
                    s_instance.Load(textAsset.text);
                }
                else
                {
                    Debug.LogError("[{{ $.Prefix }}{{ pascal .Struct.Name }}{{ $.TableSuffix }}] {{ .Name }}.json not found in Resources/{{ $.ResourceFolder }}/");
                }
            }
        }
        return s_instance;
    }
{{- end }}
}
{{- end }}
{{- if $.Namespace }}
}
{{- end }}
{{- end -}}
