// Code generated by "nestcsv"; DO NOT EDIT.

using System;
using System.IO;
{{- if .ResourceFolder }}
using UnityEngine;
{{- end }}
{{ if .Namespace }}
namespace {{ .Namespace }}
{
{{ end -}}
public abstract class {{ .Prefix }}TableBase
{
    public abstract string TableName { get; }

    public abstract object GetRows();

    public abstract void Load(string jsonString);

    public virtual void LoadFromFile(string basePath)
    {
        var filePath = Path.Combine(basePath, TableName + ".json");
        Load(File.ReadAllText(filePath));
    }
{{- if .ResourceFolder }}

    public virtual void LoadFromResources(string resourceFolder)
    {
        var resourcePath = string.IsNullOrEmpty(resourceFolder) ? TableName : resourceFolder + "/" + TableName;
        var textAsset = Resources.Load<TextAsset>(resourcePath);
        if (textAsset == null)
        {
            Debug.LogError("[" + GetType().Name + "] " + TableName + ".json not found in Resources/" + resourcePath);
            return;
        }
        Load(textAsset.text);
    }
{{- end }}
}
{{- if .Namespace }}
}
{{- end }}
