// Code generated by "nestcsv"; DO NOT EDIT.

using System.Collections.Generic;
using System.Text;
{{ if .Namespace }}
namespace {{ .Namespace }}
{
{{ end -}}
public partial class {{ .Prefix }}TableHolder
{
{{- range .Tables }}
    public {{ $.Prefix }}{{ pascal .Name }}{{ $.TableSuffix }} {{ pascal .Name }} { get; } = new {{ $.Prefix }}{{ pascal .Name }}{{ $.TableSuffix }}();
{{- end }}

    public IReadOnlyList<{{ .Prefix }}TableBase> GetTables()
    {
        return new {{ .Prefix }}TableBase[]
        {
{{- range .Tables }}
            {{ pascal .Name }},
{{- end }}
        };
    }

    public {{ .Prefix }}TableBase GetTable(string tableName)
    {
        switch (tableName)
        {
{{- range .Tables }}
            case "{{ .Name }}": return {{ pascal .Name }};
{{- end }}
            default: return null;
        }
    }

    public T Get<T>() where T : {{ .Prefix }}TableBase
    {
{{- range .Tables }}
        if (typeof(T) == typeof({{ $.Prefix }}{{ pascal .Name }}{{ $.TableSuffix }})) return (T)(object){{ pascal .Name }};
{{- end }}
        return null;
    }

    public void LoadFromFile(string basePath)
    {
        foreach (var table in GetTables())
        {
            table.LoadFromFile(basePath);
        }
{{- if .Singleton }}
        Instance = this;
{{- end }}
    }

    public static {{ .Prefix }}TableHolder LoadFrom(string basePath)
    {
        var holder = new {{ .Prefix }}TableHolder();
        holder.LoadFromFile(basePath);
        return holder;
    }

    public bool LoadFromJsonMap(IReadOnlyDictionary<string, string> jsonBySheet)
    {
        var success = true;
        foreach (var kv in jsonBySheet)
        {
            var table = GetTable(kv.Key);
            if (table == null || !table.Load(kv.Value))
            {
                success = false;
            }
        }
        return success;
    }

    public bool LoadFromBytesMap(IReadOnlyDictionary<string, byte[]> bytesBySheet)
    {
        var success = true;
        foreach (var kv in bytesBySheet)
        {
            var table = GetTable(kv.Key);
            if (table == null || !table.Load(Encoding.UTF8.GetString(kv.Value)))
            {
                success = false;
            }
        }
        return success;
    }
{{- if .ResourceFolder }}

    public void LoadFromResources(string resourceFolder = "{{ .ResourceFolder }}")
    {
        foreach (var table in GetTables())
        {
            table.LoadFromResources(resourceFolder);
        }
{{- if .Singleton }}
        Instance = this;
{{- end }}
    }

    public static {{ .Prefix }}TableHolder LoadFromResourcesFolder(string resourceFolder = "{{ .ResourceFolder }}")
    {
        var holder = new {{ .Prefix }}TableHolder();
        holder.LoadFromResources(resourceFolder);
        return holder;
    }
{{- end }}
{{- if .Singleton }}

    public static {{ .Prefix }}TableHolder Instance { get; private set; }

    public static void Register({{ .Prefix }}TableHolder holder)
    {
        Instance = holder;
    }
{{- if not .ResourceFolder }}
{{- range .Tables }}
    public static {{ $.Prefix }}{{ pascal .Name }}{{ $.TableSuffix }} {{ pascal .Name }}{{ $.TableSuffix }} => Instance.{{ pascal .Name }};
{{- end }}
{{- end }}
{{- end }}
}
{{- if .Namespace }}
}
{{- end }}
