// Code generated by "nestcsv"; DO NOT EDIT.

using System;
{{ if .Namespace }}
namespace {{ .Namespace }}
{
{{ end -}}
[Serializable]
public abstract class {{ .Prefix }}TableDataBase
{
}
{{- if .Namespace }}
}
{{- end }}
