{{- with .File -}}
// Code generated by "nestcsv"; DO NOT EDIT.

package {{ $.PackageName }}

import (
{{- if .IsTable }}
    "path/filepath"
    "encoding/json"
    "os"
{{- if and .IsMap (in .IDFieldType "int" "long") }}
    "strconv"
{{- end }}
{{- end }}
{{- if has .FieldTypes "time" }}
    "time"
{{- end }}
)

{{ range append .AnonymousStructs .Struct }}
type {{ pascal .Name }} struct {
{{- range .Fields }}
    {{ pascal .Name }} {{ fieldType . }} `json:"{{ .Name }}"`
{{- end }}
}
{{ end }}

{{ if .IsTable }}
type {{ pascal .Struct.Name }}Table struct{
    {{- if .IsMap }}
    Rows map[string]{{ pascal .Struct.Name }}
    {{- else }}
    Rows []{{ pascal .Struct.Name }}
    {{- end }}
}

func (t *{{ pascal .Struct.Name }}Table) SheetName() string {
    return "{{ .Struct.Name }}"
}

func (t *{{ pascal .Struct.Name }}Table) GetRows() interface{} {
    return t.Rows
}
{{- if or .IDField .IsMap }}

func (t *{{ pascal .Struct.Name }}Table) Find(id {{ fieldPrimitiveType .IDFieldType }}) (*{{ pascal .Struct.Name }}, bool) {
    {{- if .IsMap }}
    {{- if eq .IDFieldType "int" }}
    if row, ok := t.Rows[strconv.Itoa(id)]; ok {
    {{- else if eq .IDFieldType "long" }}
    if row, ok := t.Rows[strconv.FormatInt(id, 10)]; ok {
    {{- else }}
    if row, ok := t.Rows[id]; ok {
    {{- end }}
        return &row, true
    }
    {{- else }}
    for _, row := range t.Rows {
        if row.{{ pascal .IDField.Name }} == id {
            return &row, true
        }
    }
    {{- end }}
    return nil, false
}
{{- end }}

func (t *{{ pascal .Struct.Name }}Table) Load(data []byte) error {
    return json.Unmarshal(data, &t.Rows)
}

func (t *{{ pascal .Struct.Name }}Table) LoadFromString(jsonString string) error {
    return t.Load([]byte(jsonString))
}
   
func (t *{{ pascal .Struct.Name }}Table) LoadFromFile(basePath string) error {
    file, err := os.Open(filepath.Join(basePath, "{{ .Name }}.json"))
    if err != nil {
        return err
    }
    defer file.Close()

    return json.NewDecoder(file).Decode(&t.Rows)
}
{{- end }}
{{- end -}}