{{- with .File -}}
// Code generated by "nestcsv"; DO NOT EDIT.

package {{ $.PackageName }}

import (
{{- if .IsTable }}
    "encoding/json"
    "os"
{{- if $.CacheJSON }}
    "crypto/md5"
    "encoding/hex"
{{- end }}
{{- end }}
{{- if has .FieldTypes "time" }}
    "time"
{{- end }}
)

{{ range append .AnonymousStructs .Struct }}
type {{ pascal .Name }} struct {
{{- range .Fields }}
    {{ pascal .Name }} {{ fieldType . }} `json:"{{ .Name }}"`
{{- end }}
}
{{ end }}

{{ if .IsTable }}
type {{ pascal .Struct.Name }}Table struct{
    {{- if .IsMap }}
    Rows map[string]{{ pascal .Struct.Name }}
    {{- else }}
    Rows []{{ pascal .Struct.Name }}
    {{- end }}
    {{- if $.CacheJSON }}
    rawData []byte
    checksum string
    {{- end }}
}

func (t *{{ pascal .Struct.Name }}Table) SheetName() string {
    return "{{ .Struct.Name }}"
}

func (t *{{ pascal .Struct.Name }}Table) Load() error {
    file, err := os.Open("{{ $.DataLoadPath }}")
    if err != nil {
        return err
    }
    defer file.Close()

    if err := json.NewDecoder(file).Decode(&t.Rows); err != nil {
        return err
    }
    
    {{- if $.CacheJSON }}
    t.rawData, err = json.Marshal(t.Rows)
    if err != nil {
        return err
    }
    checksum := md5.Sum(t.Data)
    t.checksum = hex.EncodeToString(checksum[:])

    {{- end }}
    return nil
}
    
{{- if $.CacheJSON }}
func (t *{{ pascal .Struct.Name }}Table) RawData() ([]byte, string) {
    return t.rawData, t.checksum
}
{{- end }}
{{- end }}
{{- end -}}