// Code generated by "nestcsv"; DO NOT EDIT.

package {{ .PackageName }}

type Tables struct{
{{- range .Tables }}
    {{ pascal .Struct.Name }} {{ pascal .Struct.Name }}Table
{{- end }}
}

func LoadTables() (*Tables, error) {
    var t Tables
{{- range .Tables }}
    if err := t.{{ pascal .Struct.Name }}.Load(); err != nil {
        return nil, err
    }
{{- end }}
    return &t, nil
}

func (t *Tables) GetBySheetName(sheetName string) TableBase {
    switch sheetName {
{{- range .Tables }}
    case "{{ .Name }}":
        return &t.{{ pascal .Struct.Name }}
{{- end }}
    default:
        return nil
    }
}