{{- with .File -}}
// Code generated by "nestcsv"; DO NOT EDIT.

package {{ $.PackageName }}

{{- if has .FieldTypes "time" }}
import (
    "time"
)
{{- end }}

{{- range .AnonymousStructs }}
{{ template "goStruct" . }}
{{ end }}
{{ template "goStruct" .Struct }}
{{- end -}}