// Code generated by "nestcsv"; DO NOT EDIT.

package {{ .PackageName }}

import (
    "encoding/json"
    "os"
{{- range .Imports }}
    "{{ . }}"
{{- end }}
)

{{ renderStruct .Table.Name .Table.Fields }}

type {{ pascal .Table.Name }}Table struct{
    Rows []{{ pascal .Table.Name }}
}

func (t *{{ pascal .Table.Name }}Table) SheetName() string {
    return "{{ .Table.Name }}"
}

func (t *{{ pascal .Table.Name }}Table) Load() error {
    file, err := os.Open("{{ .DataLoadPath }}")
    if err != nil {
        return err
    }
    defer file.Close()

    return json.NewDecoder(file).Decode(&t.Rows)
}
