{{- with .File -}}
// Code generated by "nestcsv"; DO NOT EDIT.

package {{ $.PackageName }}

import (
    "encoding/json"
    "os"
{{- if has .FieldTypes "time" }}
    "time"
{{- end }}
)

{{- range .AnonymousStructs }}
{{ template "goStruct" . }}
{{ end }}
{{ template "goStruct" .Struct }}

type {{ pascal .Struct.Name }}Table struct{
    Rows []{{ pascal .Struct.Name }}
}

func (t *{{ pascal .Struct.Name }}Table) SheetName() string {
    return "{{ .Struct.Name }}"
}

func (t *{{ pascal .Struct.Name }}Table) Load() error {
    file, err := os.Open("{{ $.DataLoadPath }}")
    if err != nil {
        return err
    }
    defer file.Close()

    return json.NewDecoder(file).Decode(&t.Rows)
}
{{- end -}}