// Code generated by "nestcsv"; DO NOT EDIT.

package {{ .PackageName }}

type TableBase interface {
    SheetName() string
    Load() error
    {{- if $.CacheJSON }}
    RawData() ([]byte, string)
    {{- end }}
}

